language: node_js
node_js:
  - '11'

cache:
  directories:
    - 'node_modules'

branches:
  only:
    - master

install:
  - npm install

script:
  - npm audit
  - npm run lint
  - npm run test
  - npm run generate
  - curl -sSL https://frama.link/get-revelio | bash
  - revelio generate -p ./dist -u https://rclement.github.io/password-police/
  - cat ./dist/.well-known/revelio.json

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  target-branch: gh-pages
  local-dir: dist
  on:
    branch: master
